DF2016 what what
forcebuds/minihacks pull request #8
Opened 2016-10-12 14:23 UTC by barfait

bringing this page kicking and screaming into the present

2016-10-18 18:46 UTC, pcon requested changes
Need to change the Ids to match the cards.

2016-10-18 18:46 UTC, pcon commented on df16/index.html
> +		<div class="row card" id="click_to_register">
Need to change this to

``id="save_some_clicks"``

2016-10-18 18:46 UTC, pcon commented on df16/index.html
> +		<div class="row card" id="automation_without_code">
Change to

``id="allinone_system"``

2016-10-18 18:46 UTC, pcon commented on df16/index.html
> +		<div class="row card" id="integration_without_code">
Change to

``id="redesign_visualforce"``

2016-10-18 18:46 UTC, pcon commented on df16/index.html
> +		<div class="row card" id="streaming">
Change to

``id="lightning_contacts"``

2016-10-18 18:46 UTC, pcon commented on df16/index.html
> +		<div class="row card" id="lightning_components">
Change to

``id="heroku"``

2016-10-18 18:46 UTC, pcon commented on df16/index.html
> +		<div class="row card" id="heroku">
Change to

``id="all_about_apis"```

2016-10-18 18:46 UTC, pcon commented on df16/index.html
> +		<div class="row card" id="analytics_api_and_d3">
Change to

``id="windows"``

2016-11-02 16:04 UTC, barfait commented on df16/index.html
> +		<div class="row card" id="analytics_api_and_d3">
no

2016-11-02 23:57 UTC, pcon commented
Duplicate PR #9

2016-11-02 23:57 UTC, closed without merging